name: nightly-build

on: 
  push:
    branches:
      - '*'
  schedule:
    - cron: 0 0 * * *

jobs:
  nightly-build:

    runs-on: ubuntu-latest

    steps:
    - name: Build
      run: echo "Nightly build"
